### PR TITLE
fix: Validate non-empty prompt before text/image generation

### LINKED ISSUE #1819: [Bug] Text Generator Node: Running with empty prompt results in 500 error and stuck execution
### Self Checks (Required)

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/giselles-ai/giselle/discussions/categories/q-a).
- [x] I have searched for existing issues [search for existing issues](https://github.com/giselles-ai/giselle/issues), including closed ones.

### Cloud or Self Hosted (Required)

Cloud

### Version (only for Self Hosted) (Optional)

9fa72c600d56df5e117b0f46be3cbbf3441cd317

### Steps to reproduce (Required)

1.  Go to the workflow editor and add a "Text generator" node.
2.  Leave the "Prompt" input field empty.
3.  Click on the "Run" button.
4.  See the 500 internal server error and the unstoppable execution state.

### Expected Behavior (Optional)

The system should perform a validation check before execution. If the "Prompt" field is empty, it should display a user-friendly error message (e.g., "Prompt cannot be empty") and prevent the execution from starting.

### Actual Behavior (Optional)

The application backend throws a 500 error, and the node enters an unstoppable execution state. The user is unable to cancel the run and must take other measures to resolve the stuck process.

### Additional Context (Optional)

**Title:** Bug: 500 Error and Unstoppable Execution on Text Generator Node with Empty Prompt

**Error Logs:**
```
Error: Prompt cannot be empty
    at j (.next/server/chunks/2222.js:5:5770)
    at i (.next/server/chunks/2222.js:5:5500)
    at Object.execute (.next/server/chunks/2222.js:6:113854)
    at j (.next/server/chunks/2222.js:6:36474)
    at async Object.generateText (.next/server/chunks/2222.js:6:77434)
    at async handler (.next/server/chunks/2222.js:18:8669)
    at async (.next/server/chunks/2222.js:6:3171)
    at async Object.generateText (.next/server/chunks/2222.js:6:3319)
    at async (.next/server/chunks/2222.js:6:13119)
```

**Suggested Fix:**

Implement a front-end or back-end validation check to ensure the "Prompt" field is not empty before initiating the generation process. If it is empty, prevent the execution and return an informative error message to the user.

### PR DESCRIPTION
**Pull request by WashizuRyo**
## Summary
Add frontend validation for empty prompts in Text Generator and Image Generator nodes to prevent 500 errors and stuck execution.

## Related Issue
Fixes #1819

## Changes
  - Added empty prompt validation to `run-button.tsx` for both Text Generator and Image Generator nodes
  - Show error messages with node names when prompts are empty
  - Prevent backend execution to avoid 500 errors
  - Created shared isPromptEmpty utility function in editor/lib/validate-prompt.ts
  - Disable Generate button if prompt is empty in image-generation-node-properties-panel
## Testing
  1. Add a text generation node or image generation node to the workflow
  2. Leave the prompt field empty (no text entered)
  3. Click the "Run" button in the workflow toolbar
  4. Verify that an error toast appears with message "Please enter a prompt for node: [node name]"
  5. Confirm that no backend error occurs
  6. Verify that workflow execution does not start (no stuck execution state)

___

### **PR Type**
Bug fix, Enhancement

___

### **Description**
- Add frontend validation for empty prompts in text/image generation nodes

- Prevent 500 errors and stuck execution states

- Disable generate buttons when prompts are empty

- Create shared prompt validation utility function

___

### Diagram Walkthrough

```mermaid
flowchart LR
  A["Empty Prompt Input"] --> B["Validation Check"]
  B --> C["Show Error Message"]
  B --> D["Disable Generate Button"]
  C --> E["Prevent Backend Execution"]
  D --> E
```

<details> <summary><h3> File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>validate-prompt.ts</strong><dd><code>Add shared prompt validation utility</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

internal-packages/workflow-designer-ui/src/editor/lib/validate-prompt.ts

<ul><li>Create new utility function <code>isPromptEmpty</code><br> <li> Handle both JSON and plain text prompt formats<br> <li> Remove whitespace and unicode spaces for validation</ul>

</details>

  </td>
  <td><a href="https://github.com/giselles-ai/giselle/pull/1848/files#diff-9da341165ce3fe95634c435da1df3c706561cf0fa474eea19da1a19426d0c3f5">+12/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Disable image generation button for empty prompts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

internal-packages/workflow-designer-ui/src/editor/properties-panel/image-generation-node-properties-panel/index.tsx

<ul><li>Import <code>isPromptEmpty</code> validation function<br> <li> Disable Generate button when prompt is empty<br> <li> Add prompt validation to existing usage limits check</ul>

</details>

  </td>
  <td><a href="https://github.com/giselles-ai/giselle/pull/1848/files#diff-a45b1e18cc18aaa3a96fc447d8ae2e9138abb9f12b4da800373da10eb9194072">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Refactor text generation prompt validation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

internal-packages/workflow-designer-ui/src/editor/properties-panel/text-generation-node-properties-panel/index.tsx

<ul><li>Replace inline prompt validation with shared utility<br> <li> Remove duplicate validation logic<br> <li> Use <code>isPromptEmpty</code> function for button disable state</ul>

</details>

  </td>
  <td><a href="https://github.com/giselles-ai/giselle/pull/1848/files#diff-b1f2287bb552bf4b22b33e8ad29c9c365a3e751e24ee9b8f29eb16687aba37d6">+2/-12</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>run-button.tsx</strong><dd><code>Add run-time prompt validation checks</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx

<ul><li>Add pre-execution validation for text/image generation nodes<br> <li> Show error toast when empty prompts detected<br> <li> Prevent workflow execution with empty prompts<br> <li> Import node type checking functions</ul>

</details>

  </td>
  <td><a href="https://github.com/giselles-ai/giselle/pull/1848/files#diff-8a9745738738ef2c3b8f9ac4e66ea3a2abdefa3e5b53e53845092b4165130db6">+17/-2</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

</details>

___

## Summary by CodeRabbit

- New Features
  - Prevents starting runs when any text or image generation node has an empty prompt; shows an error if input is missing.
  - Generate buttons on text and image nodes are disabled when prompts are empty.
  - Prompts containing only whitespace (including full-width spaces) or empty JSON content are treated as empty for consistent validation.

### CODE REVIEW

**Comment by shige** [comment]
@codex review

**Comment by WashizuRyo** [comment]
@shige 

Currently, text and image generation can be triggered via shortcuts even if the prompt is empty.
Can we fix this in this pull request?

refs: https://github.com/giselles-ai/giselle/pull/1848#discussion_r2357746776, https://github.com/giselles-ai/giselle/pull/1848#discussion_r2357746787

**Comment by WashizuRyo** [comment]
✅ https://github.com/giselles-ai/giselle/pull/1848#issuecomment-3305684987

**Comment by shige** [comment]
> Currently, text and image generation can be triggered via shortcuts even if the prompt is empty. Can we fix this in this pull request?

@WashizuRyo 
Yes!
It can be executed by pressing Command + Enter, so please fix this.

File: internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx [hunk 1]
```diff
@@ -79,11 +84,21 @@ function RunOptionItem({
...
 	const { createAndStartAct } = useActController();
-	const { toast } = useToasts();
+	const { toast, error } = useToasts();
 
 	return async (item: RunItem) => {
+		for (const nodeId of item.nodeIds) {
+			const node = data.nodes.find((n) => n.id === nodeId);
+			if (node && (isTextGenerationNode(node) || isImageGenerationNode(node))) {
+				if (isPromptEmpty(node.content.prompt)) {
+					error(`Please enter a prompt for node: ${node.name || node.id}`);
```
Comment (shige) [inline internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx]: IMO:

I thought that displaying the node-id in the error message would be incomprehensible, so I thought it would be fine to simply write a message like "Please fill in the prompt to run."

image

**Comment by WashizuRyo** [comment]
@shige 
I fixed a bug where text and image generation could be triggered via the keyboard shortcut even if the prompt was empty, and updated the error message based on the review.

Could you review it again?

**Comment by shige** [comment]
@codex review

**Comment by shige** [comment]
🚀
