### PR TITLE
fix: Workflow doesn't run with only a Generator Node, despite 'submitted successfully' message

### LINKED ISSUE #1584: Bug: Workflow doesn't run with only a Generator Node, despite 'submitted successfully' message
### Self Checks (Required)

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/giselles-ai/giselle/discussions/categories/q-a).
- [x] I have searched for existing issues [search for existing issues](https://github.com/giselles-ai/giselle/issues), including closed ones.

### Cloud or Self Hosted (Required)

Cloud

### Version (only for Self Hosted) (Optional)
a2f703fa313e689ae04a5bb5ea698852e5f70ce9

### Steps to reproduce (Required)

1. Create a new workflow.
2. Add a single Generator Node to the canvas.
3. Click the "Run" button.

https://github.com/user-attachments/assets/cfe5b02b-3e0c-4906-9968-593654d8297a

### Expected Behavior (Optional)

The workflow should execute, and the Generator Node should produce its expected output.

### Actual Behavior (Optional)

A "Workflow submitted successfully" dialog appears, but the workflow does not run, and no output is generated.

### Additional Context (Optional)

This issue appears to be specific to workflows containing only a single Generator Node. Workflows with multiple nodes, or with a single node of a different type, execute as expected.

### PR DESCRIPTION
**Pull request by WashizuRyo**
## Summary
 Fix isolated operation node execution by passing nodeId to createAndStartAct and handling isolated nodes in the execution pipeline.

## Related Issue
 Fixes #1584 

## Changes
  1. **Pass nodeId for isolated node execution** (`use-act-controller.tsx`, `run-button.tsx`)
     - Detect when `connectionIds.length === 0` and `nodeIds.length === 1`
     - Pass `nodeId` parameter to `createAndStartAct` for isolated node execution

  2. **Handle isolated operation node execution** (`create-act.ts`)
     - When no connections are found and `nodeId` is provided
     - Find and add the isolated operation node to the execution pipeline

## Testing
  1. Add a Generator Node (Text Generation, Image Generation, Query, Action) to the workspace
  2. Select the node and configure the prompt/settings
  3. Click the Run button
  4. Verify the generator produces output successfully

https://github.com/user-attachments/assets/3db3e5d0-fb6d-4ef7-8b9a-d4a04667446d

## Other Information
 Previously, single operation nodes could not be executed because they had no connections, causing the execution pipeline to skip them. This change enables isolated operation node execution while maintaining backward
  compatibility.

Note: The original issue description mentioned "workflows with a single node of a different type execute as expected," but this was incorrect. In reality, no single nodes could be executed independently before this fix.

___

### **PR Type**
Bug fix

___

### **Description**
- Fix isolated operation node execution by detecting single nodes

- Pass nodeId parameter to createAndStartAct for isolated execution

- Handle isolated nodes in execution pipeline when no connections exist

- Enable single Generator/Operation nodes to run independently

___

### Diagram Walkthrough

```mermaid
flowchart LR
  A["Run Button Click"] --> B["Detect Isolated Node"]
  B --> C["Pass nodeId Parameter"]
  C --> D["createAndStartAct"]
  D --> E["Handle Isolated Node"]
  E --> F["Add to Execution Pipeline"]
```

<details> <summary><h3> File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>run-button.tsx</strong><dd><code>Add isolated node detection logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx

<ul><li>Detect isolated node execution when connectionIds is empty and single <br>nodeId<br> <li> Pass nodeId parameter to createAndStartAct for isolated nodes</ul>

</details>

  </td>
  <td><a href="https://github.com/giselles-ai/giselle/pull/1657/files#diff-8a9745738738ef2c3b8f9ac4e66ea3a2abdefa3e5b53e53845092b4165130db6">+5/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>use-act-controller.tsx</strong><dd><code>Update act controller interface</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

packages/giselle/src/react/act/use-act-controller.tsx

<ul><li>Add nodeId parameter to CreateAndStartActParams interface<br> <li> Pass nodeId to client.createAct method call</ul>

</details>

  </td>
  <td><a href="https://github.com/giselles-ai/giselle/pull/1657/files#diff-ea44dd1bb97d3fb72a58a5b3d63808253775e5b88253df3fc4a91d73f432ef57">+7/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>create-act.ts</strong><dd><code>Handle isolated node execution</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

packages/giselle/src/engine/acts/create-act.ts

<ul><li>Handle isolated operation node execution when no connections found<br> <li> Find and add isolated operation node to execution pipeline<br> <li> Check if node is operation type before adding</ul>

</details>

  </td>
  <td><a href="https://github.com/giselles-ai/giselle/pull/1657/files#diff-d1164f6b5e3c560e815ba9626316e75dcccdf1cb820edc3254a9d0d02e4df59b">+10/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

</details>

___

## Summary by CodeRabbit

* **New Features**
  * Run a single, isolated node (no connections) directly from the editor.
  * Isolated runs create an execution scoped to that node while preserving inputs and existing run settings.
  * Enables quicker testing and validation of individual steps without constructing full workflows.

### CODE REVIEW

**Comment by shige** [comment]
I did my OATs! ✅ 

@giselles-ai/giselle-developers 
Could you review codes when you have a time?

File: packages/giselle/src/engine/acts/create-act.ts [hunk 1]
```diff
@@ -88,6 +88,16 @@ export async function createAct(
...
+	// Handle isolated operation node execution when no connections are found
+	if (nodes.length === 0 && args.nodeId !== undefined) {
+		const isolatedNode = workspace.nodes.find(
+			(node) => node.id === args.nodeId,
+		);
+		if (isolatedNode && isOperationNode(isolatedNode)) {
+			nodes.push(isolatedNode);
+		}
+	}
+
```
Comment (toyamarinyon) [inline packages/giselle/src/engine/acts/create-act.ts]: Suggestion: Consider renaming isolatedNode to singleNode

The variable name isolatedNode might be overcomplicated. Since we're handling the case where a single node needs to be executed without connections, singleNode is
  simpler and clearer.

```ts
// Handle single node execution when no connections are found
if (nodes.length === 0 && args.nodeId !== undefined) {
    const singleNode = workspace.nodes.find(
        (node) => node.id === args.nodeId,
    );
    if (singleNode && isOperationNode(singleNode)) {
        nodes.push(singleNode);
    }
}
```

This makes the code more concise and the intent clearer - we're simply finding and adding a single node for execution.

File: internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx [hunk 2]
```diff
@@ -87,8 +87,13 @@ function useRunAct() {
 		for (const nodeId of item.nodeIds) {
 			setUiNodeState(nodeId, { highlighted: false });
 		}
+
+		const isIsolatedNodeRun =
+			item.connectionIds.length === 0 && item.nodeIds.length === 1;
+		const nodeId = isIsolatedNodeRun ? item.nodeIds[0] : undefined;
```
Comment (toyamarinyon) [inline internal-packages/workflow-designer-ui/src/editor/v2/components/run-button.tsx]: Suggestion: Consider renaming isIsolatedNodeRun to isSingleNodeRun

The variable name isIsolatedNodeRun might be slightly misleading since "isolated" doesn't inherently convey the "single node" constraint. The actual condition
  checks for both:
  - No connections (connectionIds.length === 0)
  - Single node (nodeIds.length === 1)

Since the primary purpose is to identify when we're running a single node (to extract its ID on line 93), isSingleNodeRun would be simpler and more accurate.

```ts
const isSingleNodeRun =
      item.connectionIds.length === 0 && item.nodeIds.length === 1;
const nodeId = isSingleNodeRun ? item.nodeIds[0] : undefined;
```

This makes the intent clearer - we're checking if this is a single-node execution, and the "no connections" part is an implementation detail rather than the core
  concept.

**Comment by WashizuRyo** [comment]
Thank you for the review!  
I’ve refactored the code.  
"isolated" was a bit complex and potentially misleading, while "singleNode" is clearer and better represents the intended functionality.

**Comment by shige** [comment]
@toyamarinyon Could you please review the codes refactored when you have a time?

**Review by shige — APPROVED** [review]
Thank you! 🚀

**Comment by WashizuRyo** [comment]
Thank you😀
